  ## Weather prediction ##
  - platform: yr


  ## שעה ותאריך ##
  - platform: time_date
    display_options:
      - 'date_time'
      - 'time_date'
      - 'time_utc' #For Samsung Notte design / עיצוב סמסונג נוט
      - 'time'
      - 'date' 
    

  ## cloudflare ##
  #https://www.home-assistant.io/components/sensor.dnsip/    
  - platform: dnsip
    scan_interval: 300 #5 min


  # חיישן טמפ וחיישן לחות ## 
  - platform: mqtt
    name: "Second floor temperature"
    state_topic: "tele/stairs/SENSOR"
    value_template: "{{ value_json['AM2301'].Temperature }}"
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Humidity second floor"
    state_topic: "tele/stairs/SENSOR"
    value_template: "{{ value_json['AM2301'].Humidity }}"
    # homebridge_sensor_type: "humidity"
    unit_of_measurement: "%"


  
  # גוגל #
  - platform: time_date
    display_options:
      - 'time'